# shellcheck shell=bash
#=================================================================
# DXSBash settings model — shared by dxsbash-config.sh (terminal UI)
# and dxsbash-gui.sh (graphical UI)
# Repository: https://github.com/digitalxs/dxsbash
# Website: https://dxsbash.digitalxs.ca
# License: GPL-3.0
#
# Single source of truth for the user settings files, so both front
# ends always read and write exactly the same keys:
#
#   ~/.dxsbash/user.conf            sourced by bash/zsh
#   ~/.dxsbash/user.fish            fish twin (fish can't source POSIX)
#   ~/.dxsbash/custom-aliases.sh    user aliases, sourced by bash/zsh
#   ~/.dxsbash/custom-aliases.fish  generated fish twin
#   ~/.config/starship.toml         symlink to the selected preset
#
# This file is sourced, never executed: it only defines variables and
# functions and prints nothing. Adding a setting means adding it to
# DEF_*, load_settings and write_settings here — nowhere else.
#=================================================================

DXSBASH_DIR="${DXSBASH_DIR:-$HOME/linuxtoolbox/dxsbash}"
CONF_DIR="${CONF_DIR:-$HOME/.dxsbash}"
CONF_FILE="${CONF_FILE:-$CONF_DIR/user.conf}"
CONF_FISH_FILE="${CONF_FISH_FILE:-$CONF_DIR/user.fish}"
ALIAS_FILE="${ALIAS_FILE:-$CONF_DIR/custom-aliases.sh}"
ALIAS_FISH_FILE="${ALIAS_FISH_FILE:-$CONF_DIR/custom-aliases.fish}"
STARSHIP_LINK="${STARSHIP_LINK:-$HOME/.config/starship.toml}"
STARSHIP_THEMES_DIR="${STARSHIP_THEMES_DIR:-$DXSBASH_DIR/starship-themes}"

# ── Starship theme registry ───────────────────────────────────────
# Display name | filename in starship-themes/ | one-line description
# ssh-lite.toml is deliberately absent: it is selected automatically
# over SSH, not a user-facing theme.
STARSHIP_THEMES=(
    "DXS Starship|dxs-starship.toml|The DXSBash signature look — clean, informative, the default"
    "Nerd Font Symbols|nerd-font-symbols.toml|Starship defaults with Nerd Font icons for every module"
    "Bracketed Segments|bracketed-segments.toml|Minimal text, each module wrapped in [brackets] — no special fonts"
    "Pastel Powerline|pastel-powerline.toml|Soft pastel powerline blocks with rounded edges"
    "Tokyo Night|tokyo-night.toml|Deep blues and purples inspired by the Tokyo Night palette"
    "Gruvbox Rainbow|gruvbox-rainbow.toml|Warm retro Gruvbox colors in a rainbow of segments"
    "Catppuccin Powerline|catppuccin-powerline.toml|Catppuccin Mocha pastels on powerline segments"
)

# ── Defaults ──────────────────────────────────────────────────────
DEF_EDITOR="nano"
DEF_HISTSIZE=500
DEF_HISTFILESIZE=10000
DEF_FASTFETCH="true"
DEF_PROMPT_STYLE="starship"
DEF_STARSHIP_THEME="dxs-starship.toml"
DEF_SECSUMMARY="false"
DEF_SSH_LITE="true"

# ── Current (working) values ──────────────────────────────────────
CUR_EDITOR=""
CUR_HISTSIZE=""
CUR_HISTFILESIZE=""
CUR_FASTFETCH=""
CUR_PROMPT_STYLE=""
CUR_STARSHIP_THEME=""
CUR_SECSUMMARY=""
CUR_SSH_LITE=""

#=================================================================
# Settings files
#=================================================================

# Read one value from user.conf without sourcing it
_read_conf() {
    local key="$1" default="$2" val
    if [ ! -f "$CONF_FILE" ]; then
        echo "$default"
        return
    fi
    val=$(grep -E "^export ${key}=" "$CONF_FILE" 2>/dev/null \
          | head -1 \
          | sed -E 's/^export [^=]+="?([^"]*)"?$/\1/')
    echo "${val:-$default}"
}

load_settings() {
    CUR_EDITOR=$(         _read_conf "EDITOR"                 "$DEF_EDITOR")
    CUR_HISTSIZE=$(       _read_conf "HISTSIZE"               "$DEF_HISTSIZE")
    CUR_HISTFILESIZE=$(   _read_conf "HISTFILESIZE"           "$DEF_HISTFILESIZE")
    CUR_FASTFETCH=$(      _read_conf "DXSBASH_FASTFETCH"      "$DEF_FASTFETCH")
    CUR_PROMPT_STYLE=$(   _read_conf "DXSBASH_PROMPT_STYLE"   "$DEF_PROMPT_STYLE")
    CUR_STARSHIP_THEME=$( _read_conf "DXSBASH_STARSHIP_THEME" "$DEF_STARSHIP_THEME")
    CUR_SECSUMMARY=$(     _read_conf "DXSBASH_SECSUMMARY"     "$DEF_SECSUMMARY")
    CUR_SSH_LITE=$(       _read_conf "DXSBASH_SSH_LITE"       "$DEF_SSH_LITE")

    # If the starship symlink points at a known preset, trust the
    # filesystem over the conf file — users may have run setup.sh or
    # hand-edited the symlink since the conf was written. setup.sh
    # links the repo-root starship.toml, which is the DXS preset.
    if [ -L "$STARSHIP_LINK" ]; then
        local fname
        fname="$(readlink "$STARSHIP_LINK")"
        fname="${fname##*/}"
        [ "$fname" = "starship.toml" ] && fname="dxs-starship.toml"
        if theme_known "$fname"; then
            CUR_STARSHIP_THEME="$fname"
        fi
    fi
}

# Regenerate user.conf and its fish twin from the CUR_* values.
# $1 = name of the tool writing the file (shown in the header)
write_settings() {
    local writer="${1:-dxsbash}" stamp
    stamp="$(date '+%Y-%m-%d %H:%M:%S')"
    mkdir -p "$CONF_DIR"
    cat > "$CONF_FILE" <<EOF
# DXSBash User Configuration
# Generated by ${writer} on ${stamp}
# Edit with: dxsbash-config (terminal) or dxsbash-gui (graphical)
# Apply now: source ~/.bashrc  (or ~/.zshrc)

export EDITOR="${CUR_EDITOR}"
export VISUAL="${CUR_EDITOR}"
export HISTSIZE=${CUR_HISTSIZE}
export HISTFILESIZE=${CUR_HISTFILESIZE}
export DXSBASH_FASTFETCH="${CUR_FASTFETCH}"
export DXSBASH_PROMPT_STYLE="${CUR_PROMPT_STYLE}"
export DXSBASH_STARSHIP_THEME="${CUR_STARSHIP_THEME}"
export DXSBASH_SECSUMMARY="${CUR_SECSUMMARY}"
export DXSBASH_SSH_LITE="${CUR_SSH_LITE}"
EOF

    # Fish cannot source POSIX files — write a fish-syntax twin so the
    # same settings apply there (HISTSIZE has no fish equivalent).
    cat > "$CONF_FISH_FILE" <<EOF
# DXSBash User Configuration (fish)
# Generated by ${writer} on ${stamp}
# Edit with: dxsbash-config (terminal) or dxsbash-gui (graphical)

set -gx EDITOR "${CUR_EDITOR}"
set -gx VISUAL "${CUR_EDITOR}"
set -gx DXSBASH_FASTFETCH "${CUR_FASTFETCH}"
set -gx DXSBASH_PROMPT_STYLE "${CUR_PROMPT_STYLE}"
set -gx DXSBASH_STARSHIP_THEME "${CUR_STARSHIP_THEME}"
set -gx DXSBASH_SECSUMMARY "${CUR_SECSUMMARY}"
set -gx DXSBASH_SSH_LITE "${CUR_SSH_LITE}"
EOF
}

reset_settings_to_defaults() {
    CUR_EDITOR="$DEF_EDITOR"
    CUR_HISTSIZE="$DEF_HISTSIZE"
    CUR_HISTFILESIZE="$DEF_HISTFILESIZE"
    CUR_FASTFETCH="$DEF_FASTFETCH"
    CUR_PROMPT_STYLE="$DEF_PROMPT_STYLE"
    CUR_STARSHIP_THEME="$DEF_STARSHIP_THEME"
    CUR_SECSUMMARY="$DEF_SECSUMMARY"
    CUR_SSH_LITE="$DEF_SSH_LITE"
}

# Start refreshing the security-summary cache in the background, so the
# first login after enabling the feature shows real data.
prime_secsummary_cache() {
    if [ -f "$DXSBASH_DIR/secsummary.sh" ]; then
        bash "$DXSBASH_DIR/secsummary.sh" --refresh >/dev/null 2>&1 &
    fi
}

#=================================================================
# Starship themes
#=================================================================
theme_field() { # $1 = registry entry, $2 = 1 name | 2 file | 3 description
    local name file desc
    IFS='|' read -r name file desc <<< "$1"
    case "$2" in
        1) echo "$name" ;;
        2) echo "$file" ;;
        3) echo "$desc" ;;
    esac
}

theme_known() {
    local entry
    for entry in "${STARSHIP_THEMES[@]}"; do
        [ "$(theme_field "$entry" 2)" = "$1" ] && return 0
    done
    return 1
}

starship_theme_display_name() {
    local entry
    for entry in "${STARSHIP_THEMES[@]}"; do
        if [ "$(theme_field "$entry" 2)" = "$1" ]; then
            theme_field "$entry" 1
            return
        fi
    done
    echo "unknown ($1)"
}

# Point ~/.config/starship.toml at a preset. Returns 1 if the preset
# file does not exist (nothing is changed in that case).
link_starship_theme() {
    local src="$STARSHIP_THEMES_DIR/$1"
    [ -e "$src" ] || return 1
    mkdir -p "$(dirname "$STARSHIP_LINK")"
    rm -f "$STARSHIP_LINK"
    ln -s "$src" "$STARSHIP_LINK"
}

#=================================================================
# Custom aliases
#
# custom-aliases.sh holds one "alias name='command'" line per alias,
# sourced by bash and zsh. Fish gets a generated twin
# (custom-aliases.fish) rewritten after every change, because the
# quoting rules differ: POSIX single quotes cannot contain a quote
# (written as '\''), fish single quotes use \' and \\ escapes.
#=================================================================
alias_valid_name() {
    [[ "$1" =~ ^[A-Za-z_][A-Za-z0-9_.-]*$ ]]
}

# Words that must never become aliases: shell syntax in bash, zsh or
# fish, or core builtins whose shadowing breaks the shell itself
ALIAS_RESERVED=" if then else elif fi case esac for select while until do done
 in function time coproc begin end switch not and or return exit
 alias unalias set unset source export "
alias_reserved() {
    [[ "${ALIAS_RESERVED//$'\n'/ }" == *" $1 "* ]]
}

alias_file_init() {
    [ -f "$ALIAS_FILE" ] && return 0
    mkdir -p "$CONF_DIR"
    cat > "$ALIAS_FILE" <<'EOF'
# DXSBash custom aliases — managed by dxsbash-gui ("Custom aliases").
# Hand edits are fine: keep to one alias per line, in the form
#   alias name='command'
# then run dxsbash-gui once (or 'dxsbash-gui --sync-aliases') so the
# fish copy (custom-aliases.fish) is regenerated.
EOF
}

# Print "name<TAB>command" for every alias, command unescaped
alias_list() {
    [ -f "$ALIAS_FILE" ] || return 0
    local line name body
    while IFS= read -r line; do
        [[ "$line" =~ ^alias\ ([A-Za-z_][A-Za-z0-9_.-]*)=(.*)$ ]] || continue
        name="${BASH_REMATCH[1]}"
        body="${BASH_REMATCH[2]}"
        if [[ "$body" == \'*\' ]]; then
            body="${body:1:${#body}-2}"
            body="${body//\'\\\'\'/\'}"
        elif [[ "$body" == \"*\" ]]; then
            body="${body:1:${#body}-2}"
        fi
        printf '%s\t%s\n' "$name" "$body"
    done < "$ALIAS_FILE"
}

alias_get() {
    alias_list | awk -F'\t' -v n="$1" '$1 == n { sub(/^[^\t]*\t/, ""); print; exit }'
}

alias_count() {
    alias_list | grep -c . || true
}

alias_remove() {
    [ -f "$ALIAS_FILE" ] || return 0
    local line tmp="$ALIAS_FILE.tmp"
    while IFS= read -r line; do
        [[ "$line" == "alias $1="* ]] && continue
        printf '%s\n' "$line"
    done < "$ALIAS_FILE" > "$tmp" && mv "$tmp" "$ALIAS_FILE"
    alias_sync_fish
}

alias_set() {
    local name="$1" cmd="$2"
    alias_valid_name "$name" || return 1
    alias_reserved "$name" && return 1
    alias_file_init
    alias_remove "$name"
    printf "alias %s='%s'\n" "$name" "${cmd//\'/\'\\\'\'}" >> "$ALIAS_FILE"
    alias_sync_fish
}

# Regenerate custom-aliases.fish from custom-aliases.sh
alias_sync_fish() {
    mkdir -p "$CONF_DIR"
    local name cmd esc
    {
        echo "# Generated from custom-aliases.sh by DXSBash — do not edit;"
        echo "# edit custom-aliases.sh or use dxsbash-gui instead."
        while IFS=$'\t' read -r name cmd; do
            esc="${cmd//\\/\\\\}"
            esc="${esc//\'/\\\'}"
            printf "alias %s '%s'\n" "$name" "$esc"
        done < <(alias_list)
    } > "$ALIAS_FISH_FILE"
}
